// Code generated by go-swagger; DO NOT EDIT.

package event

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jplanckeel/events-tracker/models"
)

// PostAPIV1EventReader is a Reader for the PostAPIV1Event structure.
type PostAPIV1EventReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1EventReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPIV1EventCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPostAPIV1EventInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/event/] PostAPIV1Event", response, response.Code())
	}
}

// NewPostAPIV1EventCreated creates a PostAPIV1EventCreated with default headers values
func NewPostAPIV1EventCreated() *PostAPIV1EventCreated {
	return &PostAPIV1EventCreated{}
}

/*
PostAPIV1EventCreated describes a response with status code 201, with default header values.

Created
*/
type PostAPIV1EventCreated struct {
	Payload *models.ServicesEventOutput
}

// IsSuccess returns true when this post Api v1 event created response has a 2xx status code
func (o *PostAPIV1EventCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 event created response has a 3xx status code
func (o *PostAPIV1EventCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 event created response has a 4xx status code
func (o *PostAPIV1EventCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 event created response has a 5xx status code
func (o *PostAPIV1EventCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 event created response a status code equal to that given
func (o *PostAPIV1EventCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post Api v1 event created response
func (o *PostAPIV1EventCreated) Code() int {
	return 201
}

func (o *PostAPIV1EventCreated) Error() string {
	return fmt.Sprintf("[POST /api/v1/event/][%d] postApiV1EventCreated  %+v", 201, o.Payload)
}

func (o *PostAPIV1EventCreated) String() string {
	return fmt.Sprintf("[POST /api/v1/event/][%d] postApiV1EventCreated  %+v", 201, o.Payload)
}

func (o *PostAPIV1EventCreated) GetPayload() *models.ServicesEventOutput {
	return o.Payload
}

func (o *PostAPIV1EventCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServicesEventOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1EventInternalServerError creates a PostAPIV1EventInternalServerError with default headers values
func NewPostAPIV1EventInternalServerError() *PostAPIV1EventInternalServerError {
	return &PostAPIV1EventInternalServerError{}
}

/*
PostAPIV1EventInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostAPIV1EventInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this post Api v1 event internal server error response has a 2xx status code
func (o *PostAPIV1EventInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 event internal server error response has a 3xx status code
func (o *PostAPIV1EventInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 event internal server error response has a 4xx status code
func (o *PostAPIV1EventInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 event internal server error response has a 5xx status code
func (o *PostAPIV1EventInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 event internal server error response a status code equal to that given
func (o *PostAPIV1EventInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 event internal server error response
func (o *PostAPIV1EventInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1EventInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/event/][%d] postApiV1EventInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAPIV1EventInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v1/event/][%d] postApiV1EventInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAPIV1EventInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *PostAPIV1EventInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
