// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EventEventMetadata event event metadata
//
// swagger:model event.EventMetadata
type EventEventMetadata struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// duration
	Duration float64 `json:"duration,omitempty"`

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this event event metadata
func (m *EventEventMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this event event metadata based on context it is used
func (m *EventEventMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EventEventMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventEventMetadata) UnmarshalBinary(b []byte) error {
	var res EventEventMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
