// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EventEventLinks event event links
//
// swagger:model event.EventLinks
type EventEventLinks struct {

	// pull request link
	// Example: https://github.com/jplanckeel/events-tracker/pull/240
	PullRequestLink string `json:"pull_request_link,omitempty"`
}

// Validate validates this event event links
func (m *EventEventLinks) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this event event links based on context it is used
func (m *EventEventLinks) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EventEventLinks) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventEventLinks) UnmarshalBinary(b []byte) error {
	var res EventEventLinks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
